# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
 
trigger:
- master
 
pool:
  vmImage: 'windows-latest'
# Set variables
variables:
  directory: react-azure-demo
  stage: development
  serviceConnection: REACT_AZURE_DEMO
  appServiceName: reactazuredemo
 
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
 
- script: 
    npm install
  displayName: 'npm install'
  workingDirectory: $(directory)
  
- script: 
    npm run build
  displayName: 'npm build'
  workingDirectory: $(directory) 
 
- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.SourcesDirectory)
    contents: 'Dockerfile'
    targetFolder: $(Build.ArtifactStagingDirectory)/TodoApi
            
- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.SourcesDirectory)
    contents: 'azuredotnet.yaml'
    targetFolder: $(Build.ArtifactStagingDirectory)/TodoApi
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs: 
    pathtoPublish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    
    
    
    
    
    
    
    
  
