# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
 
trigger:
- master
 
pool:
  vmImage: 'ubuntu-latest'
# Set variables
variables:
  imageName: "react/nginx"
  dockerRegistryServiceConnection: "azure_portal"
  tag: "latest"
 
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
 
- script: 
    npm install
  displayName: 'npm install'
  
  
- script: 
    npm run build
  displayName: 'npm build'
  
- task: CopyFiles@2
  displayName: 'Copy files'
  inputs:
    sourceFolder: './build' 
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/react'
    cleanTargetFolder: true
    
- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.SourcesDirectory)
    contents: 'Dockerfile'
    targetFolder: $(Build.ArtifactStagingDirectory)/react  

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.SourcesDirectory)
    contents: 'default.conf'
    targetFolder: $(Build.ArtifactStagingDirectory)/react  
    
- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.SourcesDirectory)
    contents: 'azuredotnet.yaml'
    targetFolder: $(Build.ArtifactStagingDirectory)/react
    
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs: 
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: "drop"

- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(imageName)
    dockerfile: $(Build.ArtifactStagingDirectory)/react/Dockerfile
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)
    


          
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
  
